services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: nutriorxata
      POSTGRES_USER: nutriorxata
      POSTGRES_PASSWORD: nutriorxata
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nutriorxata -d nutriorxata"]
      interval: 5s
      timeout: 5s
      retries: 10

  minio:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: nutriorxata
      MINIO_ROOT_PASSWORD: nutriorxata
    command: server /data --console-address ":9001"
    ports:
      - "9100:9000"
      - "9101:9001"
    volumes:
      - minio_data:/data

  minio_init:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        until mc alias set local http://minio:9000 nutriorxata nutriorxata; do sleep 1; done
        mc mb --ignore-existing local/nutriorxata
        mc anonymous set none local/nutriorxata
        echo "minio init done"

  api:
    build:
      context: ../../apps/api
      dockerfile: Dockerfile
      target: dev
    environment:
      API_ENVIRONMENT: development
      DATABASE_URL: postgresql+psycopg://nutriorxata:nutriorxata@db:5432/nutriorxata
      API_CORS_ORIGINS: http://localhost:5173
      API_JWT_SECRET: dev-only-secret
      S3_ENDPOINT_URL: http://minio:9000
      S3_ACCESS_KEY_ID: nutriorxata
      S3_SECRET_ACCESS_KEY: nutriorxata
      S3_BUCKET_MAIN: nutriorxata
      SENDGRID_API_KEY: ""
      SENDGRID_FROM_EMAIL: ""
      PUBLIC_API_BASE_URL: http://localhost:8010/api
    ports:
      - "8010:8000"
    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_started
    volumes:
      - ../../apps/api:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  web:
    build:
      context: ../../apps/web
      dockerfile: Dockerfile
      target: dev
    environment:
      VITE_API_URL: /api
    ports:
      - "5173:5173"
    depends_on:
      - api
    volumes:
      - ../../apps/web:/app
      - web_node_modules:/app/node_modules
    command: npm run dev -- --host 0.0.0.0 --port 5173

volumes:
  postgres_data:
  minio_data:
  web_node_modules:
